# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RottenTomatoesApp' do
  pod "AFNetworking"
  pod 'SVProgressHUD'

end

target 'RottenTomatoesAppTests' do

end

